// Complete Algerian Wilayas with all baladias (communes)
export const ALGERIA_WILAYAS = [
    { code: 1, name: "Adrar", nameAr: "أدرار" },
    { code: 2, name: "Chlef", nameAr: "الشلف" },
    { code: 3, name: "Laghouat", nameAr: "الأغواط" },
    { code: 4, name: "Oum El Bouaghi", nameAr: "أم البواقي" },
    { code: 5, name: "Batna", nameAr: "باتنة" },
    { code: 6, name: "Béjaïa", nameAr: "بجاية" },
    { code: 7, name: "Biskra", nameAr: "بسكرة" },
    { code: 8, name: "Béchar", nameAr: "بشار" },
    { code: 9, name: "Blida", nameAr: "البليدة" },
    { code: 10, name: "Bouira", nameAr: "البويرة" },
    { code: 11, name: "Tamanrasset", nameAr: "تمنراست" },
    { code: 12, name: "Tébessa", nameAr: "تبسة" },
    { code: 13, name: "Tlemcen", nameAr: "تلمسان" },
    { code: 14, name: "Tiaret", nameAr: "تيارت" },
    { code: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو" },
    { code: 16, name: "Alger", nameAr: "الجزائر" },
    { code: 17, name: "Djelfa", nameAr: "الجلفة" },
    { code: 18, name: "Jijel", nameAr: "جيجل" },
    { code: 19, name: "Sétif", nameAr: "سطيف" },
    { code: 20, name: "Saïda", nameAr: "سعيدة" },
    { code: 21, name: "Skikda", nameAr: "سكيكدة" },
    { code: 22, name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس" },
    { code: 23, name: "Annaba", nameAr: "عنابة" },
    { code: 24, name: "Guelma", nameAr: "قالمة" },
    { code: 25, name: "Constantine", nameAr: "قسنطينة" },
    { code: 26, name: "Médéa", nameAr: "المدية" },
    { code: 27, name: "Mostaganem", nameAr: "مستغانم" },
    { code: 28, name: "M'Sila", nameAr: "المسيلة" },
    { code: 29, name: "Mascara", nameAr: "معسكر" },
    { code: 30, name: "Ouargla", nameAr: "ورقلة" },
    { code: 31, name: "Oran", nameAr: "وهران" },
    { code: 32, name: "El Bayadh", nameAr: "البيض" },
    { code: 33, name: "Illizi", nameAr: "إليزي" },
    { code: 34, name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج" },
    { code: 35, name: "Boumerdès", nameAr: "بومرداس" },
    { code: 36, name: "El Tarf", nameAr: "الطارف" },
    { code: 37, name: "Tindouf", nameAr: "تندوف" },
    { code: 38, name: "Tissemsilt", nameAr: "تيسمسيلت" },
    { code: 39, name: "El Oued", nameAr: "الوادي" },
    { code: 40, name: "Khenchela", nameAr: "خنشلة" },
    { code: 41, name: "Souk Ahras", nameAr: "سوق أهراس" },
    { code: 42, name: "Tipaza", nameAr: "تيبازة" },
    { code: 43, name: "Mila", nameAr: "ميلة" },
    { code: 44, name: "Aïn Defla", nameAr: "عين الدفلى" },
    { code: 45, name: "Naâma", nameAr: "النعامة" },
    { code: 46, name: "Aïn Témouchent", nameAr: "عين تموشنت" },
    { code: 47, name: "Ghardaïa", nameAr: "غرداية" },
    { code: 48, name: "Relizane", nameAr: "غليزان" },
    { code: 49, name: "Timimoun", nameAr: "تيميمون" },
    { code: 50, name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار" },
    { code: 51, name: "Ouled Djellal", nameAr: "أولاد جلال" },
    { code: 52, name: "Béni Abbès", nameAr: "بني عباس" },
    { code: 53, name: "In Salah", nameAr: "عين صالح" },
    { code: 54, name: "In Guezzam", nameAr: "عين قزام" },
    { code: 55, name: "Touggourt", nameAr: "تقرت" },
    { code: 56, name: "Djanet", nameAr: "جانت" },
    { code: 57, name: "El M'Ghair", nameAr: "المغير" },
    { code: 58, name: "El Meniaa", nameAr: "المنيعة" },
];

// Complete baladias for all wilayas
export const BALADIAS_BY_WILAYA: Record<number, string[]> = {
    1: ["Adrar", "Tamest", "Reggane", "Timimoun", "Aoulef", "Zaouiet Kounta", "Tsabit"],
    2: ["Chlef", "Ténès", "Benairia", "El Karimia", "Tadjena", "Taougrit", "Beni Haoua", "Sobha", "Harchoun", "Ouled Fares"],
    3: ["Laghouat", "Ksar El Hirane", "Bennasser Ben Chohra", "Sidi Makhlouf", "Hassi Delaa", "Hassi R'Mel", "Ain Madhi", "Tadjmout"],
    4: ["Oum El Bouaghi", "Ain Beida", "Ain M'Lila", "Behir Chergui", "El Amiria", "Sigus", "Ain Babouche", "Berriche", "Ouled Hamla", "Dhalaa"],
    5: ["Batna", "Barika", "Merouana", "Seriana", "Menaa", "El Madher", "Tazoult", "N'Gaous", "Ain Touta", "Arris", "Tkout", "Ras El Aioun"],
    6: ["Béjaïa", "Amizour", "Ferraoun", "Taourirt Ighil", "Chellata", "Sidi Aich", "Akbou", "Seddouk", "Tazmalt", "Adekar", "Aokas", "Tichy", "Souk El Thenine", "Kherrata"],
    7: ["Biskra", "Tolga", "Ouled Djellal", "Sidi Okba", "Sidi Khaled", "El Kantara", "Zeribet El Oued", "Foughala", "Djemorah", "M'Chouneche", "El Outaya"],
    8: ["Béchar", "Taghit", "Béni Abbès", "Kénadsa", "Abadla", "Igli", "Tabelbala", "Ouled Khoudir"],
    9: ["Blida", "Boufarik", "Larbaa", "Oued El Alleug", "Bouinan", "Soumaa", "Mouzaia", "Bougara", "Beni Mered", "Ouled Yaïch", "Chebli", "Meftah", "Souhane"],
    10: ["Bouira", "Chorfa", "Ain Bessem", "Bir Ghbalou", "Lakhdaria", "M'Chedallah", "Sour El Ghozlane", "Kadiria", "Haizer", "Aomar", "El Asnam", "Bordj Okhriss"],
    11: ["Tamanrasset", "In Salah", "In Guezzam", "Tazrouk", "In Ghar", "Idles"],
    12: ["Tébessa", "Bir El Ater", "Cheria", "El Aouinet", "Negrine", "Hammamet", "Ouenza", "El Kouif", "Morsott", "El Ogla", "Bekkaria", "Boukhadra"],
    13: ["Tlemcen", "Bensekrane", "Nedroma", "Ghazaouet", "Remchi", "Hennaya", "Maghnia", "Sabra", "Marsa Ben M'Hidi", "Ouled Mimoun", "Sebdou", "Beni Snous", "Fellaoucene"],
    14: ["Tiaret", "Medroussa", "Ain Bouchekif", "Frenda", "Sougueur", "Mahdia", "Ksar Chellala", "Rahouia", "Meghila", "Mechraa Safa", "Dahmouni", "Hamadia"],
    15: ["Tizi Ouzou", "Ain El Hammam", "Akbil", "Freha", "Souk El Thenine", "Makouda", "Draa El Mizan", "Tizi Rached", "Azazga", "Azeffoun", "Tigzirt", "Beni Douala", "Ouaguenoun", "Larbaa Nath Irathen", "Ifigha", "Bouzeguene", "Ouacif"],
    16: ["Alger Centre", "Sidi M'Hamed", "El Madania", "Belouizdad", "Bab El Oued", "Bologhine", "Casbah", "Oued Koriche", "Bir Mourad Raïs", "El Biar", "Bouzareah", "Birtouta", "Birkhadem", "El Harrach", "Baraki", "Oued Smar", "Bachdjerrah", "Hussein Dey", "Kouba", "Bourouba", "Dar El Beida", "Bab Ezzouar", "Ben Aknoun", "Dely Ibrahim", "Hammamet", "Raïs Hamidou", "Djasr Kasentina", "El Mouradia", "Hydra", "Mohammadia", "Bordj El Kiffan", "El Magharia", "Beni Messous", "Les Eucalyptus", "Birmandreis", "Bachdjerrah", "Sidi Moussa", "Ain Taya", "Bordj El Bahri", "El Marsa", "H Dey", "Rouiba", "Reghaia", "Ain Benian", "Staoueli", "Zeralda", "Mahelma", "Rahmania", "Souidania", "Cheraga", "Ouled Fayet", "El Achour", "Draria", "Douera", "Baba Hassen", "Khraicia", "Saoula", "Tessala El Merdja", "Khraissia"],
    17: ["Djelfa", "Ain Oussera", "Dar Chioukh", "Hassi Bahbah", "Messaad", "Birine", "Charef", "Faidh El Botma", "Ain El Ibel", "Moudjbara", "El Idrissia", "Had Sahary"],
    18: ["Jijel", "El Milia", "Taher", "Chekfa", "El Ancer", "Ziama Mansouria", "Texenna", "Djimla", "Sidi Maarouf", "Settara", "El Aouana"],
    19: ["Sétif", "Ain El Kebira", "Bougaa", "Ain Oulmene", "Babor", "El Eulma", "Ain Azel", "Hammam Sokhna", "Ain Arnat", "Guenzet", "Salah Bey", "Ain Lahdjar", "Beni Aziz", "Boutaleb", "Amoucha", "Beni Ourtilane"],
    20: ["Saïda", "Ain El Hadjar", "Ouled Khaled", "Moulay Larbi", "Youb", "Hounet", "Sidi Boubekeur", "El Hassasna"],
    21: ["Skikda", "El Hadaiek", "Azzaba", "Djendel", "Collo", "Tamalous", "Ain Zouit", "El Harrouch", "Ramdane Djamel", "Salah Bouchaour", "Oued Z'hor", "Ouled Attia", "Beni Zid"],
    22: ["Sidi Bel Abbès", "Tessala", "Sfisef", "Ain El Berd", "Telagh", "Merine", "Ras El Ma", "Ben Badis", "Ain Tindamine", "Ain Thrid", "Moulay Slissen", "Sidi Ali Boussidi", "Hassi Zahana", "Tabia", "Amarnas"],
    23: ["Annaba", "Berrahal", "El Hadjar", "Ain Berda", "El Bouni", "Sidi Amar", "Chetaibi", "Seraidi", "El Eulma"],
    24: ["Guelma", "Bouchegouf", "Héliopolis", "Hammam Debagh", "Ain Makhlouf", "Oued Zenati", "Ain Sandel", "Khezara", "Nechmaya", "Beni Mezline"],
    25: ["Constantine", "El Khroub", "Ain Smara", "Zighoud Youcef", "Hamma Bouziane", "Ibn Ziad", "Didouche Mourad", "Ouled Rahmoune", "Ain Abid", "Beni Hamiden", "El Meridj"],
    28: ["M'Sila", "Bou Saada", "Sidi Aïssa", "Ain El Hadjel", "Hammam Dalaa", "Ouled Derraj", "Berhoum", "Magra", "Chellal", "Ouled Addi Guebala", "Benzouh", "Medjedel", "Slim", "Ain El Melh", "Dehahna", "Khoubana", "M'Cif", "Maadid"],
    26: ["Médéa", "Berrouaghia", "Tablat", "Ksar Boukhari", "Ouled Antar", "Ain Boucif", "Aziz", "Chahbounia", "El Omaria", "Si Mahdjoub", "Benchicao"],
    27: ["Mostaganem", "Ain Tedles", "Hassi Mameche", "Sidi Ali", "Ain Nouissy", "Mesra", "Bouguirat", "Sidi Lakhdar", "Achaacha", "Khadra", "Stidia", "Fornaka"],
    29: ["Mascara", "Tizi", "Ghriss", "Mohammadia", "Sig", "Oued El Abtal", "Bou Hanifia", "Ain Fekan", "Tighenif", "Oggaz", "Hachem", "Tighennif", "Aouf"],
    30: ["Ouargla", "Touggourt", "Hassi Messaoud", "Rouissat", "Ain Beida", "N'Goussa", "Tebesbest", "Zaouia El Abidia", "Hassi Ben Abdellah", "Sidi Khouiled", "Témacine"],
    31: ["Oran", "Es Senia", "Bir El Djir", "Arzew", "Bethioua", "Ain El Turk", "Mers El Kebir", "Boutlelis", "Hassi Bounif", "Hassi Ben Okba", "Gdyel", "Sidi Chami", "Ain El Kerma", "Oued Tlelat", "Hassi Mefsoukh", "Sidi Ben Yebka", "Messerghin", "Boufatis", "Marsat El Hadjadj", "El Braya", "Hassi Bounif", "El Karma", "El Ancor"],
    32: ["El Bayadh", "Rogassa", "Stitten", "Brezina", "Boualem", "El Abiodh Sidi Cheikh", "Ain El Orak", "Ghassoul", "Bougtob", "El Mehara", "Kef El Ahmar", "Chellala"],
    33: ["Illizi", "Djanet", "Debdeb", "Bordj Omar Driss", "Bordj El Haouasse"],
    34: ["Bordj Bou Arreridj", "Ras El Oued", "Bordj Ghdir", "Mansourah", "Medjana", "El Achir", "El Hamadia", "Ain Taghrout", "Bordj Zemoura", "Hasnaoua", "Khelil", "Teniet En Nasr", "El Main"],
    35: ["Boumerdès", "Boudouaou", "Dellys", "Naciria", "Bordj Menaiel", "Baghlia", "Khemis El Khechna", "Thenia", "Isser", "Zemmouri", "Si Mustapha", "Tidjelabine", "Ouled Moussa", "Corso", "Ouled Hadadj", "Timezrit"],
    36: ["El Tarf", "Bouhadjar", "Ben M'Hidi", "Bougous", "El Kala", "Ain El Assel", "Bouteldja", "Besbes", "Drean", "Chihani", "Chebaita Mokhtar", "Berrihane", "El Aioun"],
    37: ["Tindouf", "Oum El Assel"],
    38: ["Tissemsilt", "Bordj Bou Naama", "Theniet El Had", "Lardjem", "Melaab", "Sidi Lantri", "Beni Chaib", "Larbaa", "Ammari", "Bordj Emir Abdelkader", "Layoune", "Khemisti"],
    39: ["El Oued", "Robbah", "Oued El Alenda", "Bayadha", "Nakhla", "Guemar", "Kouinine", "Reguiba", "Hamraia", "Taghzout", "Debila", "Hassani Abdelkrim", "Hassi Khalifa", "Taleb Larbi", "Douar El Ma", "Sidi Aoun", "Trifaoui", "Magrane", "Beni Guecha", "Ourmas", "Still", "M'Rara", "Sidi Khellil", "Tenedla", "El Ogla"],
    40: ["Khenchela", "Bouhmama", "El Hamma", "Ain Touila", "Kais", "Baghai", "El Oueldja", "Yabous", "Tamza", "Ensigha", "Ouled Rechache", "El Mahmal", "M'Sara", "M'Toussa", "Babar", "Cherchar", "Djellal", "Taouzianat"],
    41: ["Souk Ahras", "Sedrata", "Haddada", "Mechroha", "Ouled Driss", "Tiffech", "Zaarouria", "Taoura", "Drea", "Hanancha", "Khedara", "Merahna", "Ouled Moumen", "Bir Bouhouche", "M'Daourouch", "Oum El Adhaim", "Ain Zana", "Ain Soltane", "Ouillen", "Sidi Fredj", "Safel El Ouiden", "Ragouba", "Khemissa", "Oued Keberit", "Terraguelt", "Zouabi"],
    42: ["Tipaza", "Cherchell", "Hadjout", "Kolea", "Damous", "Bou Ismail", "Ahmer El Ain", "Fouka", "Bourkika", "Khemisti", "Aghabal", "Menaceur", "Larhat", "Aghbal", "Sidi Amar", "Gouraya", "Nador", "Chaiba", "Ain Tagourait", "Sidi Ghiles", "Messelmoun", "Sidi Rached", "Kolea"],
    43: ["Mila", "Ferdjioua", "Chelghoum Laid", "Oued Athmania", "Ain Beida Harriche", "Teleghma", "Tadjenanet", "Benyahia Abderrahmane", "Oued Seguen", "Ahmed Rachedi", "Sidi Merouane", "Bouhatem", "Rouached", "Tessala Lemtai", "Grarem Gouga"],
    44: ["Ain Defla", "Khemis Miliana", "El Attaf", "El Abadia", "Djendel", "Boumedfaa", "Miliana", "Ain Bouyahia", "El Amra", "Bathia", "Rouina", "Ain Lechiakh", "Oued Chorfa", "Bordj Emir Khaled", "Tacheta Zougagha", "Bir Ould Khelifa", "Hammam Righa", "Hoceinia", "Tiberkanine", "Djelida", "Zeddine", "Ain Torki", "El Maine", "Mekhatria", "Barbouche", "Djemaa Ouled Cheikh", "Arib", "Ain Soltane", "Tarik Ibn Ziad", "Belaas", "Oued Djemaa", "Oued Fodda"],
    45: ["Naâma", "Mecheria", "Ain Sefra", "Tiout", "Sfissifa", "Moghrar", "Assela", "Djeniene Bourezg", "Ain Ben Khelil", "Makman Ben Amer", "Kasdir", "El Biod"],
    46: ["Ain Témouchent", "Hammam Bou Hadjar", "Beni Saf", "El Malah", "Sidi Ben Adda", "Ouled Boudjemaa", "Ain Tolba", "El Amria", "Hassi El Ghella", "Hassasna", "Ouled Kihal", "Chaabet El Ham", "Sidi Boumediene", "Aghlal", "Terga", "Ain El Arbaa", "Tamzoura", "Chentouf", "Sidi Safi", "Oulhaca El Gheraba", "Oued Berkeche", "Aoubellil", "El Messaid", "Oued Sabah", "Ouled Boudjemaa", "Bouzedjar", "Sidi Ouriach"],
    47: ["Ghardaïa", "El Menia", "Berriane", "Metlili", "Guerrara", "El Atteuf", "Zelfana", "Sebseb", "Bounoura", "Hassi Fehal", "Hassi Gara"],
    48: ["Relizane", "Oued Rhiou", "Yellel", "Zemmoura", "Djidiouia", "Ain Tarek", "Mazouna", "Kalaa", "Oued Essalem", "Ouarizane", "Mendes", "Sidi M'Hamed Ben Ali", "El Hamadna", "Sidi Lazreg", "Ramka", "Ammi Moussa", "El Matmar", "Sidi Khettab", "Mediouna", "Ain Rahma", "Yellel", "Beni Dergoun", "Beni Zentis", "Oued Rhiou", "Ouled Aiche", "El Guettar", "Hamri", "El Hassi", "Had Echkalla", "Bendaoud", "Dar Ben Abdellah", "Lahlef", "Oued El Djemaa", "Ouled Sidi Mihoub"],
    49: ["Timimoun", "Ouled Said", "Tinerkouk", "Deldoul", "Charouine", "Aougrout", "Ksar Kaddour", "Metarfa"],
    50: ["Bordj Badji Mokhtar", "Timiaouine"],
    51: ["Ouled Djellal", "Ras El Miad", "Doucen", "Chaiba", "Besbes", "Sidi Khaled"],
    52: ["Béni Abbès", "Beni Ikhlef", "El Ouata", "Kerzaz", "Timoudi", "Ksabi"],
    53: ["In Salah", "In Ghar", "Foggaret Ezzaouia"],
    54: ["In Guezzam", "Tin Zaouatine"],
    55: ["Touggourt", "Témacine", "Tebesbest", "Zaouia El Abidia", "Blidet Amor", "El Hadjira", "Nezla", "M'Naguer", "Taibet"],
    56: ["Djanet", "Bordj El Haouasse"],
    57: ["El M'Ghair", "Djamaa", "Sidi Amrane", "Still", "Oum Touyour", "Sidi Khelil", "Tenedla", "M'Rara"],
    58: ["El Meniaa", "Hassi Gara", "Hassi Fehal", "Mansoura"],
};

export function getBaladiasByWilaya(wilayaCode: number): string[] {
    return BALADIAS_BY_WILAYA[wilayaCode] || ["Centre"];
}
